title: Product
type: fields
columns:
    - width: 2/3
        fields:
          details:
            label: Product details
            type: headline
            numbered: false
          back:
            label: back
            type: info
            width: 1/4
            text: |
              <a href="/panel/pages/prints#products">back to products</a><br />
          uuid:
            label: Product ID
            width: 1/3
            readonly: true
            translate: false 
            type: text
            value: "{{ page.uuid }}"
          description:
            label: Description
            help: Details for the product page
            type: textarea
            required: true
          published:
            label: Published
            type: date
            help: Publishing date (December 21, 2017).
            required: true
            default: today
            width: 1/3
          meta:
            width: 1/3
            label: Meta
            help: Small text for the cart
            type: text
            default: 'Signed, unmounted print on Ilford Multigrade FB Classic paper.'
          type:
            width: 1/3
            label: Attribute
            help: Product attribute (print, zine...)
            type: select
            options:
                print: print
                zine: zine
            required: true
            default: print
          variants:
            label: Variants
            type: structure
            required: true
            fields:
              name:
                label: Variant name
                type:  text
                help: Describe variant
                required: true
              price:
                label: Price
                type:  text
                width: 1/3
                help: Numbers only
                required: true
                min: 0
              stock:
                label: Quantity in stock
                type: text
                width: 1/3
                help: Leave blank for unlimited stock
                min: 0
              suuid:
                label: SKU
                width: 1/3
                readonly: true
                translate: false 
                type: text
                value: "{{ page.uuid }}"

    - width: 1/3
        fields:
          uploads:
            label: Images
            required: true
            type: files
            query: page.images
            layout: list
            multiple: true