title: Config
type: fields
headline: Config
fields:
  author:
    label: Author
    type:  text
    width: 1/4
  keywords:
    label: Keywords
    type:  tags
    width: 3/4
  description:
    label: Description
    type:  textarea
  copyright:
    label: Copyright
    type:  textarea
  terms:
    label: Terms and Conditions
    help: terms text for store checkout
    type:  textarea