title: Config
type: fields
headline: Config
fields:
  cdn:
    label: CDN
    type:  toggle
    default: true
    help: turn off before publishing
    width: 1/2
  author:
    label: Author
    type:  text
    width: 1/2
  description:
    label: Description
    type:  textarea
  keywords:
    label: Keywords
    type:  tags
  copyright:
    label: Copyright
    type:  textarea
  terms:
    label: Terms and Conditions
    help: terms text for store checkout
    type:  textarea